application: techstorm2013
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: style
- url: /images
  static_dir: Images
- url: .*
  script: techstorm2013.application


libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest